In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("E:/NLP/data/WELFake_Dataset.csv")

In [5]:
df.head()

Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1           1                                                NaN   
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3           3  Bobby Jindal, raised Hindu, uses story of Chri...   
4           4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [6]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [7]:
df.head()

title  \
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1                                                NaN   
2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3  Bobby Jindal, raised Hindu, uses story of Chri...   
4  SATAN 2: Russia unvelis an image of its terrif...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
1     Did they post their votes for Hillary already?      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1

In [8]:
# df=pd.DataFrame(df, columns=['title' ,'text' , 'label'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   71576 non-null  object
 1   text    72095 non-null  object
 2   label   72134 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 1.7+ MB


In [10]:
df.shape

(72134, 3)

In [11]:
# check for null
df.isnull().sum()

title    558
text      39
label      0
dtype: int64

In [12]:
df.dropna(inplace=True)

In [13]:
df.head()

title  \
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3  Bobby Jindal, raised Hindu, uses story of Chri...   
4  SATAN 2: Russia unvelis an image of its terrif...   
5  About Time! Christian Group Sues Amazon and SP...   

                                                text  label  
0  No comment is expected from Barack Obama Membe...      1  
2   Now, most of the demonstrators gathered last ...      1  
3  A dozen politically active pastors came here f...      0  
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1  
5  All we can say on this one is it s about time ...      1

In [14]:
df.shape

(71537, 3)

In [15]:
x=df.drop('label', axis=1)

In [16]:
y=df['label']

In [17]:
x.shape

(71537, 2)

In [18]:
y.shape

(71537,)

In [20]:
!pip install tensorflow

  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ---------------------------------------- 0.0/331.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/331.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/331.8 MB 1.4 MB/s eta 0:04:04
   ---------------------------------------- 0.1/331.8 MB 656.4 kB/s eta 0:08:26
   ---------------------------------------- 0.1/331.8 MB 655.4 kB/s eta 0:08:27
   ---------------------------------------- 0.1/331.8 MB 658.7 kB/s eta 0:08:24
   ---------------------------------------- 0.2/331.8 MB 657.6 kB/s eta 0:08:25
   ---------------------------------------- 0.2/331.8 MB 700.2 kB/s eta 0:07:54
   ---------------------------------------- 0.2/331.8 MB 623.6 kB/s eta 0:08:52
   ---------------------------------------- 0.2/331.8 MB 627.5 kB/s eta 0:08:49
   ---------------------

ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/8f/aa/ba0014cc4659328dc818a28827be78e6d97312ab0cb98105a770924dc11e/absl_py-2.3.1-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B35D85F1D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))



In [19]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
tf.__version__

'2.19.0'

In [ ]:
# !pip install tf-keras


In [ ]:
from tensorflow.keras.layers import Embedding ,Input
from tensorflow.keras.models import Sequential
from tf_keras.utils import pad_sequences
from tf_keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
# vocab size
voc_size=5000

In [ ]:
messages=x.copy()

In [ ]:
messages

title  \
0      LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
2      UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
3      Bobby Jindal, raised Hindu, uses story of Chri...   
4      SATAN 2: Russia unvelis an image of its terrif...   
5      About Time! Christian Group Sues Amazon and SP...   
...                                                  ...   
72129  Russians steal research on Trump in hack of U....   
72130   WATCH: Giuliani Demands That Democrats Apolog...   
72131  Migrants Refuse To Leave Train At Refugee Camp...   
72132  Trump tussle gives unpopular Mexican leader mu...   
72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text  
0      No comment is expected from Barack Obama Membe...  
2       Now, most of the demonstrators gathered last ...  
3      A dozen politically active pastors came here f...  
4      The RS-28 Sarmat missile, dubbed Satan 2, will...  
5      All we can say on this one is it s about time ...  
...                                                  ...  
72129  WASHINGTON (Reuters) - Hackers believed to be ...  
72130  You know, because in fantasyland Republicans n...  
72131  Migrants Refuse To Leave Train At Refugee Camp...  
72132  MEXICO CITY (Reuters) - Donald Trump’s combati...  
72133  Goldman Sachs Endorses Hillary Clinton For Pre...  

[71537 rows x 2 columns]

In [ ]:
messages['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

index                                              title  \
0          0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...   
1          2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...   
2          3  Bobby Jindal, raised Hindu, uses story of Chri...   
3          4  SATAN 2: Russia unvelis an image of its terrif...   
4          5  About Time! Christian Group Sues Amazon and SP...   
...      ...                                                ...   
71532  72129  Russians steal research on Trump in hack of U....   
71533  72130   WATCH: Giuliani Demands That Democrats Apolog...   
71534  72131  Migrants Refuse To Leave Train At Refugee Camp...   
71535  72132  Trump tussle gives unpopular Mexican leader mu...   
71536  72133  Goldman Sachs Endorses Hillary Clinton For Pre...   

                                                    text  
0      No comment is expected from Barack Obama Membe...  
1       Now, most of the demonstrators gathered last ...  
2      A dozen politically active pastors came here f...  
3      The RS-28 Sarmat missile, dubbed Satan 2, will...  
4      All we can say on this one is it s about time ...  
...                                                  ...  
71532  WASHINGTON (Reuters) - Hackers believed to be ...  
71533  You know, because in fantasyland Republicans n...  
71534  Migrants Refuse To Leave Train At Refugee Camp...  
71535  MEXICO CITY (Reuters) - Donald Trump’s combati...  
71536  Goldman Sachs Endorses Hillary Clinton For Pre...  

[71537 rows x 3 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
# Dataset prepocessing

In [ ]:
from nltk.stem import WordNetLemmatizer
lmt=WordNetLemmatizer()

In [ ]:
corpus=[]

In [ ]:
for i in range(0, len(messages)):
  # print(i)
  review=re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review=review.lower()
  review=review.split()

  review=[lmt.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review=" ".join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
66537
66538
66539
66540
66541
66542
66543
66544
66545
66546
66547
66548
66549
66550
66551
66552
66553
66554
66555
66556
66557
66558
66559
66560
66561
66562
66563
66564
66565
66566
66567
66568
66569
66570
66571
66572
66573
66574
66575
66576
66577
66578
66579
66580
66581
66582
66583
66584
66585
66586
66587
66588
66589
66590
66591
66592
66593
66594
66595
66596
66597
66598
66599
66600
66601
66602
66603
66604
66605
66606
66607
66608
66609
66610
66611
66612
66613
66614
66615
66616
66617
66618
66619
66620
66621
66622
66623
66624
66625
66626
66627
66628
66629
66630
66631
66632
66633
66634
66635
66636
66637
66638
66639
66640
66641
66642
66643
66644
66645
66646
66647
66648
66649
66650
66651
66652
66653
66654
66655
66656
66657
66658
66659
66660
66661
66662
66663
66664
66665
66666
66667
66668
66669
66670
66671
66672
66673
66674
66675
66676
66677
66678
66679
66680
66681
66682
66683
66684
66685
66686
66687
66688
66689
66690
66691
66692
66693
66694
6

In [ ]:
corpus

['law enforcement high alert following threat cop white blacklivesmatter fyf terrorist video',
 'unbelievable obama attorney general say charlotte rioter peaceful protester home state north carolina video',
 'bobby jindal raised hindu us story christian conversion woo evangelicals potential bid',
 'satan russia unvelis image terrifying new supernuke western world take notice',
 'time christian group sue amazon splc designation hate group',
 'dr ben carson targeted irs never audit spoke national prayer breakfast',
 'house intel chair trump russia fake story evidence anything video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipeline leak underscore danger dakota access pipeline',
 'gop senator smacked punchable alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint official oversee puerto rico relief',
 'watch hilarious ad call question health aging clinton crime family 

In [ ]:
len(corpus)

71537

In [ ]:
# One hot encoding

In [ ]:
onehot_repr=[one_hot(words, voc_size) for words in corpus]
onehot_repr

[[1930, 365, 2552, 2953, 680, 4771, 23, 3920, 306, 271, 1430, 1650],
 [373, 429, 860, 3026, 9, 136, 2992, 3200, 2654, 3878, 220, 3143, 500, 1650],
 [4991, 4556, 2199, 3820, 1794, 298, 3646, 4510, 939, 1955, 230, 4648],
 [4508, 3904, 1381, 2111, 1775, 1752, 4493, 1318, 3869, 1674, 3613],
 [4019, 3646, 3436, 2601, 439, 2075, 931, 2817, 3436],
 [3019, 1186, 4530, 64, 176, 3062, 4252, 4360, 1273, 2109, 1549],
 [4981, 2361, 2960, 1286, 3904, 1977, 298, 2429, 1635, 1650],
 [3368,
  3037,
  464,
  269,
  2585,
  1220,
  4034,
  1723,
  2060,
  3368,
  3849,
  3405,
  3731,
  726,
  1650],
 [2800, 1617, 3789, 3639, 2489, 1975, 1935, 1617],
 [2533, 2609, 189, 1919, 3102, 1646, 1411, 4426],
 [966, 2689, 4518, 125, 2225, 4029, 2156, 2936, 2156, 2810],
 [269, 3894, 1286, 938, 2287, 2503, 4978, 3559, 4887],
 [4225, 158, 802, 3894, 2673, 4804, 1928, 3250, 909, 1527, 925],
 [915, 800, 1934, 4520, 3613, 2430, 4613, 4740, 2425, 167],
 [4255, 983, 4832, 3864, 2197, 4981, 458],
 [2623, 3566, 4455, 4753, 

In [ ]:
corpus[1]

'unbelievable obama attorney general say charlotte rioter peaceful protester home state north carolina video'

In [ ]:
onehot_repr[1]

[373, 429, 860, 3026, 9, 136, 2992, 3200, 2654, 3878, 220, 3143, 500, 1650]

In [ ]:
# Padding


In [ ]:
len(max(corpus))

59

In [ ]:
sentence_length= 60
embedded_docs= pad_sequences(onehot_repr, padding='pre', maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0 ...  271 1430 1650]
 [   0    0    0 ... 3143  500 1650]
 [   0    0    0 ... 1955  230 4648]
 ...
 [   0    0    0 ...  705 1245 4559]
 [   0    0    0 ... 4252 3473 1171]
 [   0    0    0 ...  361 3250  380]]


# Creating LSTM model

In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Input(shape=(sentence_length,)))
model.add(Embedding(voc_size, embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 60, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
x_final.shape , y_final.shape


((71537, 60), (71537,))

In [ ]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(x_final,y_final , test_size=0.25 , random_state=33)

In [ ]:
# Model training

In [ ]:
print(xtrain.dtype, ytrain.dtype)
print(type(xtrain), type(ytrain))


int32 int64
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


# Adding dropouts

In [ ]:
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Input(shape=(sentence_length,)))
model.add(Embedding(voc_size, embedding_vector_features))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 60, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60, 40)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.fit(xtrain[:5000] , ytrain[:5000] , validation_data=(xtest , ytest), epochs=10 , batch_size=64)

Epoch 1/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 16s 205ms/step - accuracy: 0.8629 - loss: 0.3293 - val_accuracy: 0.8534 - val_loss: 0.3273
Epoch 2/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 16s 203ms/step - accuracy: 0.9308 - loss: 0.1907 - val_accuracy: 0.8614 - val_loss: 0.3395
Epoch 3/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 18s 225ms/step - accuracy: 0.9509 - loss: 0.1302 - val_accuracy: 0.8478 - val_loss: 0.3810
Epoch 4/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 17s 212ms/step - accuracy: 0.9682 - loss: 0.0951 - val_accuracy: 0.8472 - val_loss: 0.4556
Epoch 5/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 17s 214ms/step - accuracy: 0.9698 - loss: 0.0783 - val_accuracy: 0.8503 - val_loss: 0.4945
Epoch 6/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 22s 228ms/step - accuracy: 0.9875 - loss: 0.0440 - val_accuracy: 0.8428 - val_loss: 0.5357
Epoch 7/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 17s 219ms/step - accuracy: 0.9853 - loss: 0.0438 - val_accuracy: 0.8405 - val_loss: 0.6610
Epoch 8/10
79/79 ━━━━━━━━━━━━━━━━━━━━ 17s 210ms/step - accuracy: 0.9906 - loss: 0.0281 - val_accu

In [ ]:
import pickle
pickle.dump(model, open('lstm.pkl', 'wb'))

In [ ]:
y_pred=model.predict(xtest)


559/559 ━━━━━━━━━━━━━━━━━━━━ 10s 17ms/step


In [ ]:
y_pred=np.where(y_pred > 0.5, 1, 0)

In [ ]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix , roc_auc_score

In [ ]:
print("Accuracy score :" , accuracy_score(ytest , y_pred))
print("Confusion matrix :" , confusion_matrix(ytest , y_pred))
print("Classification report :" , classification_report(ytest , y_pred))

Accuracy score : 0.8901313950237629
Confusion matrix : [[7632 1189]
 [ 776 8288]]
Classification report :               precision    recall  f1-score   support

           0       0.91      0.87      0.89      8821
           1       0.87      0.91      0.89      9064

    accuracy                           0.89     17885
   macro avg       0.89      0.89      0.89     17885
weighted avg       0.89      0.89      0.89     17885

